In [2]:
import numpy as np
import json

physics_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/property_params.json'
physics_params = json.load(open(physics_path, 'r'))
physics_params

{'particle_radius': 0.03,
 'num_particles': 2000,
 'granular_scale': 0.1602763376071644,
 'num_granular': 36,
 'distribution_r': 0.20897663659937937,
 'dynamic_friction': 0.49655835953723326,
 'granular_mass': 6.494351719359895,
 'tool': 2.0,
 'dustpan': 1.0}

In [3]:
steps_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/steps.npy'
steps = np.load(steps_path)
steps

array([  0,  69, 138, 207, 276])

In [4]:
sponge_state_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/sponge_points.npy'
sponge_states = np.load(sponge_state_path)
sponge_states.shape

(345, 100, 3)

In [5]:
dustpan_state_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/dustpan_points.npy'
dustpan_states = np.load(dustpan_state_path)
dustpan_states.shape

(345, 100, 3)

In [7]:
particles_pos_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/particles_pos.npy'
particles_pos = np.load(particles_pos_path)
particles_pos.shape

(345, 2000, 3)

In [9]:
import torch
# Create a 2x3 tensor
x = torch.arange(6).reshape(2, 3)
print("Original Tensor:")
print(x)

# Transpose the tensor, making it non-contiguous
y = x.transpose(0, 1)
print("\nTransposed Tensor:")
print(y)

# Check if the transposed tensor is contiguous
print("\nIs Transposed Tensor Contiguous?:", y.is_contiguous())

# Make it contiguous
y_contiguous = y.contiguous()
print("\nContiguous Tensor:")
print(y_contiguous)

# Check if the new tensor is contiguous
print("\nIs New Tensor Contiguous?:", y_contiguous.is_contiguous())

Original Tensor:
tensor([[0, 1, 2],
        [3, 4, 5]])

Transposed Tensor:
tensor([[0, 3],
        [1, 4],
        [2, 5]])

Is Transposed Tensor Contiguous?: False

Contiguous Tensor:
tensor([[0, 3],
        [1, 4],
        [2, 5]])

Is New Tensor Contiguous?: True


In [3]:
import numpy as np
dustpan_points_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/dustpan_points.npy'
dustpan_points = np.load(dustpan_points_path)
print(dustpan_points.shape)
dustpan_points[0]

(345, 100, 3)


array([[-9.02431931e-01,  7.66416022e-01, -4.27702193e+00],
       [-9.41843254e-01,  6.31203903e-01, -3.12663642e+00],
       [ 9.00650102e-01,  5.48839199e-01, -4.28212622e+00],
       [ 9.00890738e-01,  5.10302403e-01, -2.95675899e+00],
       [ 1.31666057e-01,  5.09608455e-01, -3.02939591e+00],
       [ 1.33847836e-01,  5.09924155e-01, -2.99302266e+00],
       [-1.27160953e-01,  5.12074098e-01, -2.91283874e+00],
       [-9.41828754e-01,  5.15921417e-01, -4.25008747e+00],
       [-9.44107927e-01,  8.09579957e-01, -4.24093835e+00],
       [ 3.79626540e-02,  5.08893307e-01, -4.23462161e+00],
       [ 9.09285606e-01,  1.05922243e+00, -4.22861934e+00],
       [-2.07255029e-02,  1.05792310e+00, -4.24612836e+00],
       [-1.06560942e-01,  5.08474376e-01, -3.22572021e+00],
       [ 7.17344647e-01,  5.74944349e-01, -3.33072776e+00],
       [ 5.08513433e-01,  5.59467711e-01, -3.21914989e+00],
       [-9.04223650e-01,  1.04726861e+00, -4.21523009e+00],
       [ 2.02900957e-01,  6.16749343e-01

In [4]:
import numpy as np
sponge_points_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/sponge_points.npy'
sponge_points = np.load(sponge_points_path)
print(sponge_points.shape)
sponge_points[0]

(345, 100, 3)


array([[0.59648409, 0.72      , 4.58420153],
       [0.77204692, 0.72      , 4.66912407],
       [0.8767981 , 0.72      , 4.64775172],
       [1.30635453, 0.72      , 4.89771016],
       [1.24610922, 0.72      , 4.8166777 ],
       [1.10430165, 0.72      , 4.81107735],
       [0.99673366, 0.72      , 4.85506952],
       [0.96957472, 0.72      , 4.7426955 ],
       [0.68044722, 0.72      , 4.83934631],
       [0.68000939, 0.72      , 4.72370693],
       [0.77471434, 0.72      , 4.44513991],
       [0.70532091, 0.72      , 4.54041525],
       [0.80735007, 0.72      , 4.55050446],
       [0.84209017, 0.72      , 4.89655793],
       [0.82203062, 0.72      , 4.75930645],
       [0.89696482, 0.72      , 4.81816979],
       [0.94020959, 0.72      , 4.54154136],
       [1.33726058, 0.72      , 4.74246658],
       [1.25083446, 0.72      , 4.52511609],
       [1.21258067, 0.72      , 4.6229975 ],
       [1.18329475, 0.72      , 5.00553158],
       [1.18764018, 0.72      , 4.91195857],
       [1.

In [6]:
sponge_points[1]

array([[0.55901839, 0.72      , 4.24354651],
       [0.73458122, 0.72      , 4.32846906],
       [0.8393324 , 0.72      , 4.3070967 ],
       [1.26888882, 0.72      , 4.55705515],
       [1.20864351, 0.72      , 4.47602269],
       [1.06683595, 0.72      , 4.47042234],
       [0.95926796, 0.72      , 4.5144145 ],
       [0.93210902, 0.72      , 4.40204048],
       [0.64298152, 0.72      , 4.4986913 ],
       [0.64254368, 0.72      , 4.38305192],
       [0.73724863, 0.72      , 4.1044849 ],
       [0.66785521, 0.72      , 4.19976024],
       [0.76988437, 0.72      , 4.20984945],
       [0.80462447, 0.72      , 4.55590292],
       [0.78456492, 0.72      , 4.41865144],
       [0.85949911, 0.72      , 4.47751478],
       [0.90274388, 0.72      , 4.20088635],
       [1.29979488, 0.72      , 4.40181157],
       [1.21336875, 0.72      , 4.18446108],
       [1.17511497, 0.72      , 4.28234249],
       [1.14582905, 0.72      , 4.66487656],
       [1.15017447, 0.72      , 4.57130356],
       [1.

In [1]:
import numpy as np
import json
import os

epi_idx = 25
data_dir = '/mnt/sda/data/granular_sweeping_dustpan'
episode_dir = os.path.join(data_dir, 'episode_{}'.format(epi_idx))
physics_path = os.path.join(episode_dir, 'property_params.json')
physics_params = json.load(open(physics_path, 'r'))
physics_params

{'particle_radius': 0.03,
 'num_particles': 2000,
 'granular_scale': 0.14332490286144536,
 'num_granular': 48,
 'distribution_r': 0.11976484535025243,
 'dynamic_friction': 0.32657718574829464,
 'granular_mass': 1.5911187429876466,
 'tool': 2.0,
 'dustpan': 1.0}

In [3]:
import numpy as np
import json
import os

epi_idx = 24
data_dir = '/mnt/sda/data/granular_sweeping_dustpan'
episode_dir = os.path.join(data_dir, 'episode_{}'.format(epi_idx))
physics_path = os.path.join(episode_dir, 'property_params.json')
physics_params = json.load(open(physics_path, 'r'))
physics_params

{'particle_radius': 0.03,
 'num_particles': 383,
 'granular_scale': 0.10528546199192651,
 'num_granular': 24,
 'distribution_r': 0.16349764499078287,
 'dynamic_friction': 0.8887644883449333,
 'granular_mass': 5.139294668469025,
 'tool': 2.0,
 'dustpan': 1.0}