In [2]:
import numpy as np
import json

physics_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/property_params.json'
physics_params = json.load(open(physics_path, 'r'))
physics_params

{'particle_radius': 0.03,
 'num_particles': 2000,
 'granular_scale': 0.1602763376071644,
 'num_granular': 36,
 'distribution_r': 0.20897663659937937,
 'dynamic_friction': 0.49655835953723326,
 'granular_mass': 6.494351719359895,
 'tool': 2.0,
 'dustpan': 1.0}

In [3]:
steps_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/steps.npy'
steps = np.load(steps_path)
steps

array([  0,  69, 138, 207, 276])

In [5]:
sponge_state_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/sponge_states.npy'
sponge_states = np.load(sponge_state_path)
sponge_states.shape

(345, 7)

In [6]:
dustpan_state_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/dustpan_states.npy'
dustpan_states = np.load(dustpan_state_path)
dustpan_states.shape

(345, 7)

In [7]:
particles_pos_path = '/mnt/sda/data/granular_sweeping_dustpan/episode_0/particles_pos.npy'
particles_pos = np.load(particles_pos_path)
particles_pos.shape

(345, 2000, 3)

In [9]:
import torch
# Create a 2x3 tensor
x = torch.arange(6).reshape(2, 3)
print("Original Tensor:")
print(x)

# Transpose the tensor, making it non-contiguous
y = x.transpose(0, 1)
print("\nTransposed Tensor:")
print(y)

# Check if the transposed tensor is contiguous
print("\nIs Transposed Tensor Contiguous?:", y.is_contiguous())

# Make it contiguous
y_contiguous = y.contiguous()
print("\nContiguous Tensor:")
print(y_contiguous)

# Check if the new tensor is contiguous
print("\nIs New Tensor Contiguous?:", y_contiguous.is_contiguous())

Original Tensor:
tensor([[0, 1, 2],
        [3, 4, 5]])

Transposed Tensor:
tensor([[0, 3],
        [1, 4],
        [2, 5]])

Is Transposed Tensor Contiguous?: False

Contiguous Tensor:
tensor([[0, 3],
        [1, 4],
        [2, 5]])

Is New Tensor Contiguous?: True
