In [1]:
import numpy as np
import json

data_name = 'carrots'
physics_path = f'/mnt/sda/data/{data_name}/episode_0/property_params.json'
physics_params = json.load(open(physics_path, 'r'))
physics_params

{'particle_radius': 0.03,
 'num_particles': 8492,
 'granular_scale': 0.18579456176227568,
 'num_granular': 70,
 'distribution_r': 0.2694503477568251,
 'dynamic_friction': 0.6364945877501806,
 'granular_mass': 0.04459435365634299}

In [2]:
steps_path = f'/mnt/sda/data/{data_name}/episode_0/steps.npy'
steps = np.load(steps_path)
steps

array([  2,  36,  67, 108, 150, 190, 231, 277, 313, 343, 393])

In [4]:
particles_pos_path = f'/mnt/sda/data/{data_name}/episode_0/particles_pos.npy'
particles_pos = np.load(particles_pos_path)
particles_pos.shape

(393, 2000, 3)

In [2]:
processed_eef_states = np.load(f'/mnt/sda/data/{data_name}/episode_0/processed_eef_states.npy')
print(processed_eef_states.shape)
print(processed_eef_states)

(85, 5, 3)
[[[-1.52999997  0.67000041  0.04501488]
  [-2.52999997  0.67000041  0.04501488]
  [-2.02999997  0.67000041  0.04501488]
  [-1.77999997  0.67000041  0.04501488]
  [-2.27999997  0.67000041  0.04501488]]

 [[-1.52999997  0.67000041  0.04501488]
  [-2.52999997  0.67000041  0.04501488]
  [-2.02999997  0.67000041  0.04501488]
  [-1.77999997  0.67000041  0.04501488]
  [-2.27999997  0.67000041  0.04501488]]

 [[ 2.56514886  0.74998785  1.78738156]
  [ 2.72424808  0.74997521  0.80011896]
  [ 2.64469847  0.74998153  1.29375026]
  [ 2.60492366  0.74998469  1.54056591]
  [ 2.68447327  0.74997837  1.04693461]]

 ...

 [[ 0.14112373  0.54232771 -1.02012209]
  [-0.67333372  0.55621155 -1.60017923]
  [-0.26610499  0.54926963 -1.31015066]
  [-0.06249063  0.54579867 -1.16513637]
  [-0.46971936  0.55274059 -1.45516494]]

 [[ 0.21678286  0.54312269 -1.12293121]
  [-0.59760017  0.55570605 -1.70312249]
  [-0.19040865  0.54941437 -1.41302685]
  [ 0.01318711  0.54626853 -1.26797903]
  [-0.39400441 